import pyautogui
from clicks import *
import time

def install_absolute():
	double_click_image('absolute/imgs/absolute_folder.png')
	time.sleep(2)
	double_click_image('absolute/imgs/computracepic.png')
	time.sleep(3)
	press_enter()
	wait(15)
	press_enter()
	wait(1)
	press_enter()
	wait(35)
	press_enter()
	wait(3)

	right_click_image('absolute/imgs/ctmweb.png')
	wait(1)
	single_click_image('absolute/imgs/runasadmin.png')
	wait(3)
	single_click_image('absolute/imgs/allowaccess.png')
	wait(1)
	single_click_image('absolute/imgs/textbox.png')
	type_string('password')
	single_click_image('absolute/imgs/next.png')
	wait(1)
	single_click_image('absolute/imgs/testcall.png')
	wait(1)
	right_click_image('absolute/imgs/ctmtooltip.png')
	wait(0.5)
	single_click_image('absolute/imgs/close_window.png')
	wait(1)
	single_click_image('absolute/imgs/goback.png')
